### ISSUE TITLE
use VNB14NV04TR-E for fans and compression release solenoid

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-harley81#10]
we have around 5 high current consumers between 5A and 7A

let's use VNB14NV04TR-E

**Comment by NMSTEC** [comment]
would also like to have 3 high and 3 low channels for the "extra functions" connector. We plan on installing a Electric Shift on this thing, and in production version we'd like to keep these as for water functions we want.

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/147499758-cc490eca-f899-4f27-b7d9-1e9f1f4cda2e.png)
@NMSTEC We have several Proteus outputs of 3.5 A (lowside) and 1.3 A (highside). Is this enough or do you need more current?

**Comment by rusefillc** [comment]
let's have diodes on all of these just in case.

**Comment by NMSTEC** [comment]
3.5 is not enough for fans, acr, or additional functions. We discussed this
in some other git issue, and we did some good estimates on the google drive
file that I am not able to access right now.

Absolute minimum was 7amp for acr I believe? And that's constant current.

**Comment by rusefillc** [comment]
@NMSTEC it was not worded perfectly. Schematics snippet shows 10A mosfet for fans, acr, or additional function.
