### ISSUE TITLE
VR-discrete option with jumpers 

### ISSUE THREAD

**Issue by rusefillc** [rusefi/proteus-harley81#5]
let's have two ways to process VR

1) proteus as us, with one set of jumpers
2) using VR-discrete on adapter via another set of jumpers

that way we validate VR-discrete on HD before we go Hellen

**Comment by Qwerty-OFF** [comment]
Done, Hellen as default
![image](https://user-images.githubusercontent.com/4116383/147500452-402d371f-60d7-45bb-9ae0-2093cb3263e5.png)
